from .pcmffi import (
    ProcMaps,
    MemoryRegion,
    PROCMAPS_SUCCESS,
    PROCMAPS_ERROR_OPEN_MAPS_FILE,
    PROCMAPS_ERROR_READ_MAPS_FILE,
    PROCMAPS_ERROR_MALLOC_FAIL,
    PROCMAPS_MAP_FILE,
    PROCMAPS_MAP_STACK,
    PROCMAPS_MAP_STACK_TID,
    PROCMAPS_MAP_VDSO,
    PROCMAPS_MAP_VSYSCALL,
    PROCMAPS_MAP_VVAR,
    PROCMAPS_MAP_HEAP,
    PROCMAPS_MAP_ANON_PRIV,
    PROCMAPS_MAP_ANON_MMAPS,
    PROCMAPS_MAP_ANON_SHMEM,
    PROCMAPS_MAP_OTHER,
)

__title__ = "pcmffi"

__author__ = "Salmi Younes"
__copyright__ = "Copyright (c) 2026 " + __author__
__license__ = "MIT"

__all__ = [
    "ProcMaps",
    "MemoryRegion",
    "PROCMAPS_SUCCESS",
    "PROCMAPS_ERROR_OPEN_MAPS_FILE",
    "PROCMAPS_ERROR_READ_MAPS_FILE",
    "PROCMAPS_ERROR_MALLOC_FAIL",
    "PROCMAPS_MAP_FILE",
    "PROCMAPS_MAP_STACK",
    "PROCMAPS_MAP_STACK_TID",
    "PROCMAPS_MAP_VDSO",
    "PROCMAPS_MAP_VSYSCALL",
    "PROCMAPS_MAP_VVAR",
    "PROCMAPS_MAP_HEAP",
    "PROCMAPS_MAP_ANON_PRIV",
    "PROCMAPS_MAP_ANON_MMAPS",
    "PROCMAPS_MAP_ANON_SHMEM",
    "PROCMAPS_MAP_OTHER",
]
